In [1]:
import torch
from layers import BezierLayer

In [2]:
bl = BezierLayer(10, 20, 40)
cp = torch.rand(50, 2, 20) * 1
w = torch.rand(50, 1, 20) * 1
ipt = torch.rand(50, 10) * 1
bl(ipt, cp, w)

(tensor([[[0.6048, 0.7544, 0.7981,  ..., 0.4695, 0.5027, 0.3575],
          [0.9652, 0.8053, 0.6972,  ..., 0.3413, 0.2933, 0.3419]],
 
         [[0.0420, 0.2768, 0.3962,  ..., 0.4308, 0.4453, 0.4428],
          [0.1248, 0.4746, 0.6096,  ..., 0.5548, 0.6080, 0.6672]],
 
         [[0.4313, 0.4071, 0.4116,  ..., 0.4878, 0.5111, 0.5453],
          [0.3200, 0.4029, 0.4736,  ..., 0.2257, 0.2420, 0.4040]],
 
         ...,
 
         [[0.6239, 0.6935, 0.7528,  ..., 0.8409, 0.8934, 0.9261],
          [0.5466, 0.4745, 0.4183,  ..., 0.1868, 0.1880, 0.1972]],
 
         [[0.4355, 0.4662, 0.5834,  ..., 0.7340, 0.7045, 0.6147],
          [0.3144, 0.2875, 0.2734,  ..., 0.5892, 0.5558, 0.3872]],
 
         [[0.1356, 0.2637, 0.3415,  ..., 0.5457, 0.5556, 0.5773],
          [0.3498, 0.4831, 0.5743,  ..., 0.4705, 0.4874, 0.4913]]],
        grad_fn=<DivBackward0>),
 tensor([[[0.0000, 0.0265, 0.0555,  ..., 0.9733, 0.9896, 1.0000]],
 
         [[0.0000, 0.0163, 0.0354,  ..., 0.9738, 0.9889, 1.0000]],
 
    

In [3]:
torch.lgamma(torch.Tensor(2))

tensor([    inf, -0.0477])

In [16]:
a = torch.arange(0, 10)
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
b = a.flip((0,))
a[1] = 100
print(b)

tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
