In [1]:
import torch
from layers import BezierLayer

In [2]:
bl = BezierLayer(10, 20, 40)
cp = torch.rand(50, 2, 20) * 1
w = torch.rand(50, 1, 20) * 1
ipt = torch.rand(50, 10) * 1
bl(ipt, cp, w)

(tensor([[[0.6238, 0.7070, 0.6500,  ..., 0.2459, 0.1268, 0.0047],
          [0.8056, 0.7055, 0.7016,  ..., 0.5148, 0.4882, 0.4839]],
 
         [[0.5414, 0.3875, 0.3561,  ..., 0.2568, 0.3363, 0.4752],
          [0.6756, 0.6324, 0.5851,  ..., 0.0838, 0.0857, 0.1056]],
 
         [[0.4404, 0.5928, 0.6697,  ..., 0.8881, 0.9346, 0.9524],
          [0.4088, 0.3434, 0.3519,  ..., 0.7225, 0.6971, 0.6709]],
 
         ...,
 
         [[0.5852, 0.5926, 0.5668,  ..., 0.8898, 0.8816, 0.6075],
          [0.5425, 0.5621, 0.5475,  ..., 0.7004, 0.7529, 0.7326]],
 
         [[0.5888, 0.6323, 0.7038,  ..., 0.1148, 0.0726, 0.0339],
          [0.1304, 0.2286, 0.3053,  ..., 0.7711, 0.8661, 0.9613]],
 
         [[0.9535, 0.8302, 0.7089,  ..., 0.7515, 0.9204, 0.9778],
          [0.7676, 0.6830, 0.5919,  ..., 0.7629, 0.8004, 0.8153]]],
        grad_fn=<DivBackward0>),
 tensor([[[0.0000, 0.0308, 0.0616,  ..., 0.9559, 0.9836, 1.0000]],
 
         [[0.0000, 0.0384, 0.0659,  ..., 0.9614, 0.9879, 1.0000]],
 
    

In [3]:
torch.lgamma(torch.Tensor(2))

tensor([99.8777,     inf])

In [4]:
a = torch.tensor(10.)

In [5]:
a

tensor(10.)

In [6]:
a.requires_grad

False

In [7]:
b = torch.log(a)

In [8]:
b.requires_grad

False