In [1]:
import torch
from layers import BezierLayer

In [80]:
bl = BezierLayer(10, 20, 40)
cp = torch.rand(50, 2, 20) * 1
w = torch.rand(50, 1, 20) * 1
ipt = torch.rand(50, 10) * 1
bl(ipt, cp, w)

(tensor([[[0.9839, 0.9441, 0.9343,  ..., 0.5617, 0.4854, 0.0795],
          [0.2625, 0.2920, 0.2993,  ..., 0.4206, 0.3305, 0.6472]],
 
         [[0.6119, 0.5772, 0.5715,  ..., 0.4670, 0.4058, 0.3854],
          [0.4514, 0.4852, 0.4910,  ..., 0.4325, 0.4348, 0.4272]],
 
         [[0.5376, 0.5389, 0.5392,  ..., 0.2629, 0.3657, 0.5521],
          [0.4854, 0.4920, 0.4945,  ..., 0.6497, 0.7119, 0.8297]],
 
         ...,
 
         [[0.2330, 0.2731, 0.2812,  ..., 0.3196, 0.2388, 0.1885],
          [0.8605, 0.8325, 0.8268,  ..., 0.4753, 0.5192, 0.5601]],
 
         [[0.5155, 0.5297, 0.5331,  ..., 0.6445, 0.6823, 0.6880],
          [0.7260, 0.7326, 0.7342,  ..., 0.2350, 0.2813, 0.4345]],
 
         [[0.8502, 0.8454, 0.8439,  ..., 0.3689, 0.3202, 0.2813],
          [0.9526, 0.9361, 0.9312,  ..., 0.7021, 0.7771, 0.8344]]],
        grad_fn=<DivBackward0>),
 tensor([[0.0000, 0.0529, 0.0128,  ..., 0.0119, 0.0182, 0.0089],
         [0.0000, 0.0618, 0.0121,  ..., 0.0081, 0.0146, 0.0103],
         [0.

In [3]:
torch.lgamma(torch.Tensor(1))

tensor([inf])